import Foundation
import Observation

enum VentureCopy: Int, CaseIterable {
    case language, next, guest, account, signIn, email, password, name, agree, verify, code
    case permissions, microphone, camera, allow, skip, home, insights, assistant, care, settings
    case start, stop, example, pause, ahh, eyes, done, retry, saved, empty, download, preparing
    case send, message, unavailable, screening, guestNote, demo, call, nearby, voiceNotice, privacy, terms, cancel, signOut
}

struct VentureLanguage: Identifiable, Equatable, Sendable {
    let id: String
    let name: String
    let words: [String]
    var isRTL: Bool { ["ar", "ur"].contains(id) }
    func text(_ key: VentureCopy) -> String { words[key.rawValue] }

    // Authored offline translations. No translation service, network or English fallback.
    static let all: [VentureLanguage] = rows.map { id, name, row in
        let words = row.components(separatedBy: "|")
        precondition(words.count == VentureCopy.allCases.count, "Incomplete translation: \(id)")
        return VentureLanguage(id: id, name: name, words: words)
    }

    private static let rows: [(String, String, String)] = [
        ("en", "English", "language|continue|guest|create account|sign in|email|password|name|I agree to the terms and privacy policy|verify email|code|permissions|microphone|camera|allow|skip|home|insights|assistant|care|settings|start|stop|example|pause|say ahh for 5 seconds|look at the centre|done|try again|saved|no measurements yet|download|preparing|send|message|unavailable|Measurements, not a diagnosis.|Guest data stays in this session.|Call demonstration. No call is placed.|play call|nearby hospitals|Kokoro voice: English only.|privacy|terms|cancel|sign out"),
        ("hi", "हिन्दी", "भाषा|आगे बढ़ें|अतिथि|खाता बनाएँ|साइन इन|ईमेल|पासवर्ड|नाम|मैं नियमों और गोपनीयता नीति से सहमत हूँ|ईमेल सत्यापित करें|कोड|अनुमतियाँ|माइक्रोफ़ोन|कैमरा|अनुमति दें|छोड़ें|होम|जानकारी|सहायक|देखभाल|सेटिंग्स|शुरू करें|रोकें|उदाहरण|विराम|5 सेकंड आह कहें|बीच में देखें|पूरा|फिर प्रयास करें|सहेजा गया|अभी कोई माप नहीं|डाउनलोड|तैयारी हो रही है|भेजें|संदेश|उपलब्ध नहीं|माप हैं, निदान नहीं।|अतिथि डेटा इसी सत्र तक रहता है।|कॉल का उदाहरण। कोई कॉल नहीं की जाएगी।|कॉल सुनें|पास के अस्पताल|Kokoro की आवाज़: केवल अंग्रेज़ी।|गोपनीयता|नियम|रद्द करें|साइन आउट"),
        ("es", "Español", "idioma|continuar|invitado|crear cuenta|iniciar sesión|correo|contraseña|nombre|Acepto los términos y la política de privacidad|verificar correo|código|permisos|micrófono|cámara|permitir|omitir|inicio|datos|asistente|atención|ajustes|iniciar|detener|ejemplo|pausa|di ah durante 5 segundos|mira al centro|listo|reintentar|guardado|aún no hay mediciones|descargar|preparando|enviar|mensaje|no disponible|Mediciones, no un diagnóstico.|Los datos del invitado duran esta sesión.|Demostración. No se realiza una llamada.|escuchar llamada|hospitales cercanos|Voz Kokoro: solo inglés.|privacidad|términos|cancelar|cerrar sesión"),
        ("fr", "Français", "langue|continuer|invité|créer un compte|connexion|courriel|mot de passe|nom|J’accepte les conditions et la politique de confidentialité|vérifier le courriel|code|autorisations|microphone|caméra|autoriser|passer|accueil|mesures|assistant|soins|réglages|commencer|arrêter|exemple|pause|dites ah pendant 5 secondes|regardez le centre|terminé|réessayer|enregistré|aucune mesure pour le moment|télécharger|préparation|envoyer|message|indisponible|Des mesures, pas un diagnostic.|Les données invité restent dans cette session.|Démonstration. Aucun appel n’est passé.|écouter l’appel|hôpitaux proches|Voix Kokoro : anglais uniquement.|confidentialité|conditions|annuler|déconnexion"),
        ("de", "Deutsch", "Sprache|weiter|Gast|Konto erstellen|anmelden|E-Mail|Passwort|Name|Ich stimme den Bedingungen und dem Datenschutz zu|E-Mail bestätigen|Code|Berechtigungen|Mikrofon|Kamera|erlauben|überspringen|Start|Messwerte|Assistent|Versorgung|Einstellungen|starten|stoppen|Beispiel|Pause|5 Sekunden ah sagen|in die Mitte schauen|fertig|erneut versuchen|gespeichert|noch keine Messungen|herunterladen|wird vorbereitet|senden|Nachricht|nicht verfügbar|Messungen, keine Diagnose.|Gastdaten bleiben in dieser Sitzung.|Vorführung. Es wird nicht angerufen.|Anruf abspielen|Krankenhäuser in der Nähe|Kokoro-Stimme: nur Englisch.|Datenschutz|Bedingungen|abbrechen|abmelden"),
        ("pt", "Português", "idioma|continuar|visitante|criar conta|entrar|e-mail|senha|nome|Aceito os termos e a política de privacidade|verificar e-mail|código|permissões|microfone|câmera|permitir|pular|início|dados|assistente|cuidados|configurações|iniciar|parar|exemplo|pausa|diga ah por 5 segundos|olhe para o centro|concluído|tentar novamente|salvo|ainda sem medições|baixar|preparando|enviar|mensagem|indisponível|Medições, não um diagnóstico.|Os dados do visitante duram esta sessão.|Demonstração. Nenhuma chamada é feita.|ouvir chamada|hospitais próximos|Voz Kokoro: somente inglês.|privacidade|termos|cancelar|sair"),
        ("it", "Italiano", "lingua|continua|ospite|crea account|accedi|email|password|nome|Accetto i termini e l’informativa sulla privacy|verifica email|codice|permessi|microfono|fotocamera|consenti|salta|inizio|dati|assistente|assistenza|impostazioni|inizia|ferma|esempio|pausa|di’ ah per 5 secondi|guarda il centro|fatto|riprova|salvato|nessuna misurazione ancora|scarica|preparazione|invia|messaggio|non disponibile|Misurazioni, non una diagnosi.|I dati ospite restano in questa sessione.|Dimostrazione. Non viene effettuata una chiamata.|ascolta chiamata|ospedali vicini|Voce Kokoro: solo inglese.|privacy|termini|annulla|esci"),
        ("ar", "العربية", "اللغة|متابعة|ضيف|إنشاء حساب|تسجيل الدخول|البريد الإلكتروني|كلمة المرور|الاسم|أوافق على الشروط وسياسة الخصوصية|تأكيد البريد|الرمز|الأذونات|الميكروفون|الكاميرا|السماح|تخطي|الرئيسية|البيانات|المساعد|الرعاية|الإعدادات|ابدأ|توقف|مثال|إيقاف مؤقت|قل آه لمدة 5 ثوانٍ|انظر إلى الوسط|تم|حاول مجدداً|تم الحفظ|لا قياسات بعد|تنزيل|جارٍ التحضير|إرسال|رسالة|غير متاح|قياسات وليست تشخيصاً.|بيانات الضيف تبقى في هذه الجلسة.|عرض توضيحي. لا تُجرى مكالمة.|تشغيل المكالمة|مستشفيات قريبة|صوت Kokoro: الإنجليزية فقط.|الخصوصية|الشروط|إلغاء|تسجيل الخروج"),
        ("bn", "বাংলা", "ভাষা|চালিয়ে যান|অতিথি|অ্যাকাউন্ট তৈরি করুন|সাইন ইন|ইমেল|পাসওয়ার্ড|নাম|আমি শর্ত ও গোপনীয়তা নীতিতে সম্মত|ইমেল যাচাই করুন|কোড|অনুমতি|মাইক্রোফোন|ক্যামেরা|অনুমতি দিন|বাদ দিন|হোম|তথ্য|সহায়ক|যত্ন|সেটিংস|শুরু|থামুন|উদাহরণ|বিরতি|5 সেকেন্ড আহ বলুন|মাঝখানে তাকান|সম্পন্ন|আবার চেষ্টা করুন|সংরক্ষিত|এখনও কোনো পরিমাপ নেই|ডাউনলোড|প্রস্তুতি চলছে|পাঠান|বার্তা|উপলব্ধ নয়|পরিমাপ, রোগ নির্ণয় নয়।|অতিথির তথ্য এই সেশনেই থাকে।|কলের উদাহরণ। কোনো কল করা হবে না।|কল শুনুন|কাছের হাসপাতাল|Kokoro কণ্ঠ: শুধু ইংরেজি।|গোপনীয়তা|শর্ত|বাতিল|সাইন আউট"),
        ("ur", "اردو", "زبان|جاری رکھیں|مہمان|اکاؤنٹ بنائیں|سائن ان|ای میل|پاس ورڈ|نام|میں شرائط اور رازداری کی پالیسی سے متفق ہوں|ای میل کی تصدیق|کوڈ|اجازتیں|مائیکروفون|کیمرہ|اجازت دیں|چھوڑیں|ہوم|معلومات|معاون|نگہداشت|ترتیبات|شروع|روکیں|مثال|وقفہ|5 سیکنڈ آہ کہیں|درمیان میں دیکھیں|مکمل|دوبارہ کوشش|محفوظ|ابھی کوئی پیمائش نہیں|ڈاؤن لوڈ|تیاری جاری ہے|بھیجیں|پیغام|دستیاب نہیں|پیمائش، تشخیص نہیں۔|مہمان کا ڈیٹا اسی سیشن میں رہتا ہے۔|کال کی مثال۔ کوئی کال نہیں ہوگی۔|کال سنیں|قریبی ہسپتال|Kokoro آواز: صرف انگریزی۔|رازداری|شرائط|منسوخ|سائن آؤٹ"),
        ("pa", "ਪੰਜਾਬੀ", "ਭਾਸ਼ਾ|ਅੱਗੇ ਵਧੋ|ਮਹਿਮਾਨ|ਖਾਤਾ ਬਣਾਓ|ਸਾਈਨ ਇਨ|ਈਮੇਲ|ਪਾਸਵਰਡ|ਨਾਮ|ਮੈਂ ਸ਼ਰਤਾਂ ਅਤੇ ਪਰਦੇਦਾਰੀ ਨੀਤੀ ਨਾਲ ਸਹਿਮਤ ਹਾਂ|ਈਮੇਲ ਤਸਦੀਕ ਕਰੋ|ਕੋਡ|ਇਜਾਜ਼ਤਾਂ|ਮਾਈਕ੍ਰੋਫ਼ੋਨ|ਕੈਮਰਾ|ਇਜਾਜ਼ਤ ਦਿਓ|ਛੱਡੋ|ਹੋਮ|ਜਾਣਕਾਰੀ|ਸਹਾਇਕ|ਦੇਖਭਾਲ|ਸੈਟਿੰਗਾਂ|ਸ਼ੁਰੂ|ਰੋਕੋ|ਉਦਾਹਰਨ|ਵਿਰਾਮ|5 ਸਕਿੰਟ ਆਹ ਕਹੋ|ਵਿਚਕਾਰ ਦੇਖੋ|ਪੂਰਾ|ਫਿਰ ਕੋਸ਼ਿਸ਼ ਕਰੋ|ਸੁਰੱਖਿਅਤ|ਅਜੇ ਕੋਈ ਮਾਪ ਨਹੀਂ|ਡਾਊਨਲੋਡ|ਤਿਆਰੀ ਜਾਰੀ|ਭੇਜੋ|ਸੁਨੇਹਾ|ਉਪਲਬਧ ਨਹੀਂ|ਮਾਪ ਹਨ, ਨਿਦਾਨ ਨਹੀਂ।|ਮਹਿਮਾਨ ਦਾ ਡਾਟਾ ਇਸ ਸੈਸ਼ਨ ਵਿੱਚ ਰਹਿੰਦਾ ਹੈ।|ਕਾਲ ਦੀ ਉਦਾਹਰਨ। ਕੋਈ ਕਾਲ ਨਹੀਂ ਹੋਵੇਗੀ।|ਕਾਲ ਸੁਣੋ|ਨੇੜਲੇ ਹਸਪਤਾਲ|Kokoro ਆਵਾਜ਼: ਕੇਵਲ ਅੰਗਰੇਜ਼ੀ।|ਪਰਦੇਦਾਰੀ|ਸ਼ਰਤਾਂ|ਰੱਦ|ਸਾਈਨ ਆਊਟ"),
        ("ta", "தமிழ்", "மொழி|தொடரவும்|விருந்தினர்|கணக்கு உருவாக்கு|உள்நுழை|மின்னஞ்சல்|கடவுச்சொல்|பெயர்|விதிமுறைகளையும் தனியுரிமைக் கொள்கையையும் ஏற்கிறேன்|மின்னஞ்சலைச் சரிபார்|குறியீடு|அனுமதிகள்|ஒலிவாங்கி|கேமரா|அனுமதி|தவிர்|முகப்பு|தகவல்கள்|உதவியாளர்|பராமரிப்பு|அமைப்புகள்|தொடங்கு|நிறுத்து|எடுத்துக்காட்டு|இடைநிறுத்தம்|5 நொடிகள் ஆ என்று சொல்லவும்|மையத்தைப் பார்க்கவும்|முடிந்தது|மீண்டும் முயற்சி|சேமிக்கப்பட்டது|இன்னும் அளவீடுகள் இல்லை|பதிவிறக்கு|தயாராகிறது|அனுப்பு|செய்தி|கிடைக்கவில்லை|அளவீடுகள் மட்டுமே, நோயறிதல் அல்ல.|விருந்தினர் தரவு இந்த அமர்வில் மட்டும் இருக்கும்.|அழைப்பு விளக்கம். அழைப்பு செய்யப்படாது.|அழைப்பைக் கேள்|அருகிலுள்ள மருத்துவமனைகள்|Kokoro குரல்: ஆங்கிலம் மட்டும்.|தனியுரிமை|விதிமுறைகள்|ரத்து|வெளியேறு"),
        ("te", "తెలుగు", "భాష|కొనసాగించు|అతిథి|ఖాతా సృష్టించు|సైన్ ఇన్|ఇమెయిల్|పాస్‌వర్డ్|పేరు|నిబంధనలు మరియు గోప్యతా విధానాన్ని అంగీకరిస్తున్నాను|ఇమెయిల్ ధృవీకరించు|కోడ్|అనుమతులు|మైక్రోఫోన్|కెమెరా|అనుమతించు|దాటవేయి|హోమ్|సమాచారం|సహాయకుడు|సంరక్షణ|సెట్టింగులు|ప్రారంభించు|ఆపు|ఉదాహరణ|విరామం|5 సెకన్లు ఆ అనండి|మధ్యలో చూడండి|పూర్తయింది|మళ్లీ ప్రయత్నించు|సేవ్ అయింది|ఇంకా కొలతలు లేవు|డౌన్‌లోడ్|సిద్ధమవుతోంది|పంపు|సందేశం|అందుబాటులో లేదు|కొలతలు మాత్రమే, నిర్ధారణ కాదు.|అతిథి డేటా ఈ సెషన్‌లోనే ఉంటుంది.|కాల్ ప్రదర్శన. కాల్ చేయబడదు.|కాల్ విను|సమీప ఆసుపత్రులు|Kokoro స్వరం: ఇంగ్లీష్ మాత్రమే.|గోప్యత|నిబంధనలు|రద్దు|సైన్ అవుట్"),
        ("mr", "मराठी", "भाषा|पुढे जा|अतिथी|खाते तयार करा|साइन इन|ईमेल|पासवर्ड|नाव|मी अटी आणि गोपनीयता धोरण मान्य करतो|ईमेल पडताळा|कोड|परवानग्या|मायक्रोफोन|कॅमेरा|परवानगी द्या|वगळा|होम|माहिती|सहायक|काळजी|सेटिंग्स|सुरू करा|थांबा|उदाहरण|विराम|5 सेकंद आ म्हणा|मध्यभागी पाहा|पूर्ण|पुन्हा प्रयत्न करा|जतन केले|अजून मोजमाप नाहीत|डाउनलोड|तयारी सुरू|पाठवा|संदेश|उपलब्ध नाही|मोजमाप आहेत, निदान नाही.|अतिथी डेटा या सत्रापुरता राहतो.|कॉलचे प्रात्यक्षिक. कॉल केला जाणार नाही.|कॉल ऐका|जवळची रुग्णालये|Kokoro आवाज: फक्त इंग्रजी.|गोपनीयता|अटी|रद्द|साइन आउट"),
        ("gu", "ગુજરાતી", "ભાષા|આગળ વધો|અતિથિ|ખાતું બનાવો|સાઇન ઇન|ઈમેલ|પાસવર્ડ|નામ|હું શરતો અને ગોપનીયતા નીતિ સાથે સંમત છું|ઈમેલ ચકાસો|કોડ|પરવાનગીઓ|માઇક્રોફોન|કેમેરા|પરવાનગી આપો|છોડો|હોમ|માહિતી|સહાયક|સંભાળ|સેટિંગ્સ|શરૂ કરો|રોકો|ઉદાહરણ|વિરામ|5 સેકન્ડ આહ કહો|વચ્ચે જુઓ|પૂર્ણ|ફરી પ્રયાસ કરો|સાચવ્યું|હજુ કોઈ માપ નથી|ડાઉનલોડ|તૈયારી થઈ રહી છે|મોકલો|સંદેશ|ઉપલબ્ધ નથી|માપ છે, નિદાન નથી.|અતિથિ ડેટા આ સત્ર સુધી રહે છે.|કૉલનું ઉદાહરણ. કૉલ નહીં થાય.|કૉલ સાંભળો|નજીકની હોસ્પિટલો|Kokoro અવાજ: ફક્ત અંગ્રેજી.|ગોપનીયતા|શરતો|રદ કરો|સાઇન આઉટ"),
        ("kn", "ಕನ್ನಡ", "ಭಾಷೆ|ಮುಂದುವರಿಸಿ|ಅತಿಥಿ|ಖಾತೆ ರಚಿಸಿ|ಸೈನ್ ಇನ್|ಇಮೇಲ್|ಪಾಸ್‌ವರ್ಡ್|ಹೆಸರು|ನಿಯಮಗಳು ಮತ್ತು ಗೌಪ್ಯತಾ ನೀತಿಯನ್ನು ಒಪ್ಪುತ್ತೇನೆ|ಇಮೇಲ್ ಪರಿಶೀಲಿಸಿ|ಕೋಡ್|ಅನುಮತಿಗಳು|ಮೈಕ್ರೋಫೋನ್|ಕ್ಯಾಮೆರಾ|ಅನುಮತಿಸಿ|ಬಿಟ್ಟುಬಿಡಿ|ಮುಖಪುಟ|ಮಾಹಿತಿ|ಸಹಾಯಕ|ಆರೈಕೆ|ಸೆಟ್ಟಿಂಗ್‌ಗಳು|ಆರಂಭಿಸಿ|ನಿಲ್ಲಿಸಿ|ಉದಾಹರಣೆ|ವಿರಾಮ|5 ಸೆಕೆಂಡ್ ಆ ಎಂದು ಹೇಳಿ|ಮಧ್ಯದಲ್ಲಿ ನೋಡಿ|ಮುಗಿದಿದೆ|ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ|ಉಳಿಸಲಾಗಿದೆ|ಇನ್ನೂ ಅಳತೆಗಳಿಲ್ಲ|ಡೌನ್‌ಲೋಡ್|ಸಿದ್ಧವಾಗುತ್ತಿದೆ|ಕಳುಹಿಸಿ|ಸಂದೇಶ|ಲಭ್ಯವಿಲ್ಲ|ಅಳತೆಗಳು ಮಾತ್ರ, ರೋಗನಿರ್ಣಯವಲ್ಲ.|ಅತಿಥಿ ದತ್ತಾಂಶ ಈ ಅವಧಿಯಲ್ಲಿ ಮಾತ್ರ ಇರುತ್ತದೆ.|ಕರೆ ಪ್ರದರ್ಶನ. ಕರೆ ಮಾಡಲಾಗುವುದಿಲ್ಲ.|ಕರೆ ಕೇಳಿ|ಹತ್ತಿರದ ಆಸ್ಪತ್ರೆಗಳು|Kokoro ಧ್ವನಿ: ಇಂಗ್ಲಿಷ್ ಮಾತ್ರ.|ಗೌಪ್ಯತೆ|ನಿಯಮಗಳು|ರದ್ದು|ಸೈನ್ ಔಟ್"),
        ("ml", "മലയാളം", "ഭാഷ|തുടരുക|അതിഥി|അക്കൗണ്ട് സൃഷ്ടിക്കുക|സൈൻ ഇൻ|ഇമെയിൽ|പാസ്‌വേഡ്|പേര്|നിബന്ധനകളും സ്വകാര്യതാ നയവും അംഗീകരിക്കുന്നു|ഇമെയിൽ പരിശോധിക്കുക|കോഡ്|അനുമതികൾ|മൈക്രോഫോൺ|ക്യാമറ|അനുവദിക്കുക|ഒഴിവാക്കുക|ഹോം|വിവരങ്ങൾ|സഹായി|പരിചരണം|ക്രമീകരണങ്ങൾ|തുടങ്ങുക|നിർത്തുക|ഉദാഹരണം|വിരാമം|5 സെക്കൻഡ് ആ എന്നു പറയുക|മധ്യത്തിൽ നോക്കുക|പൂർത്തിയായി|വീണ്ടും ശ്രമിക്കുക|സംരക്ഷിച്ചു|ഇനിയും അളവുകളില്ല|ഡൗൺലോഡ്|തയ്യാറാകുന്നു|അയയ്ക്കുക|സന്ദേശം|ലഭ്യമല്ല|അളവുകൾ മാത്രം, രോഗനിർണയമല്ല.|അതിഥി ഡാറ്റ ഈ സെഷനിൽ മാത്രം നിലനിൽക്കും.|കോളിന്റെ മാതൃക. കോൾ ചെയ്യില്ല.|കോൾ കേൾക്കുക|അടുത്തുള്ള ആശുപത്രികൾ|Kokoro ശബ്ദം: ഇംഗ്ലീഷ് മാത്രം.|സ്വകാര്യത|നിബന്ധനകൾ|റദ്ദാക്കുക|സൈൻ ഔട്ട്"),
        ("zh-Hans", "简体中文", "语言|继续|访客|创建账户|登录|邮箱|密码|姓名|我同意条款和隐私政策|验证邮箱|验证码|权限|麦克风|相机|允许|跳过|首页|数据|助手|医疗|设置|开始|停止|示范|暂停|说啊并持续5秒|看向中央|完成|重试|已保存|暂无测量|下载|准备中|发送|消息|不可用|仅为测量，并非诊断。|访客数据仅保留在本次会话。|通话演示，不会拨打电话。|播放通话|附近医院|Kokoro语音：仅限英语。|隐私|条款|取消|退出登录"),
        ("ja", "日本語", "言語|続ける|ゲスト|アカウント作成|ログイン|メール|パスワード|名前|利用規約とプライバシーポリシーに同意します|メール認証|コード|権限|マイク|カメラ|許可|スキップ|ホーム|記録|アシスタント|ケア|設定|開始|停止|お手本|一時停止|5秒間「あー」と言ってください|中央を見てください|完了|再試行|保存済み|測定記録はありません|ダウンロード|準備中|送信|メッセージ|利用不可|測定であり、診断ではありません。|ゲストのデータは今回のセッションのみです。|通話のデモです。電話はかけません。|通話を再生|近くの病院|Kokoro音声：英語のみ。|プライバシー|利用規約|キャンセル|ログアウト"),
        ("ko", "한국어", "언어|계속|게스트|계정 만들기|로그인|이메일|비밀번호|이름|약관 및 개인정보 처리방침에 동의합니다|이메일 인증|코드|권한|마이크|카메라|허용|건너뛰기|홈|기록|도우미|진료|설정|시작|정지|예시|일시 정지|5초 동안 아 소리를 내세요|중앙을 보세요|완료|다시 시도|저장됨|아직 측정 기록이 없습니다|다운로드|준비 중|보내기|메시지|사용 불가|측정이며 진단이 아닙니다.|게스트 데이터는 이번 세션에만 남습니다.|통화 시연입니다. 실제로 전화하지 않습니다.|통화 재생|근처 병원|Kokoro 음성: 영어만 지원.|개인정보|약관|취소|로그아웃"),
        ("ru", "Русский", "язык|продолжить|гость|создать аккаунт|войти|почта|пароль|имя|Я принимаю условия и политику конфиденциальности|подтвердить почту|код|разрешения|микрофон|камера|разрешить|пропустить|главная|данные|помощник|помощь|настройки|начать|остановить|пример|пауза|говорите а в течение 5 секунд|смотрите в центр|готово|повторить|сохранено|измерений пока нет|скачать|подготовка|отправить|сообщение|недоступно|Измерения, а не диагноз.|Данные гостя остаются только в этой сессии.|Демонстрация. Звонок не совершается.|прослушать звонок|больницы рядом|Голос Kokoro: только английский.|конфиденциальность|условия|отмена|выйти"),
        ("tr", "Türkçe", "dil|devam|misafir|hesap oluştur|giriş yap|e-posta|şifre|ad|Koşulları ve gizlilik politikasını kabul ediyorum|e-postayı doğrula|kod|izinler|mikrofon|kamera|izin ver|atla|ana sayfa|veriler|asistan|bakım|ayarlar|başlat|durdur|örnek|duraklat|5 saniye ah deyin|ortaya bakın|tamam|tekrar dene|kaydedildi|henüz ölçüm yok|indir|hazırlanıyor|gönder|mesaj|kullanılamıyor|Ölçümler, tanı değil.|Misafir verileri bu oturumda kalır.|Arama demosu. Arama yapılmaz.|aramayı dinle|yakındaki hastaneler|Kokoro sesi: yalnızca İngilizce.|gizlilik|koşullar|iptal|çıkış yap"),
        ("vi", "Tiếng Việt", "ngôn ngữ|tiếp tục|khách|tạo tài khoản|đăng nhập|email|mật khẩu|tên|Tôi đồng ý với điều khoản và chính sách riêng tư|xác minh email|mã|quyền truy cập|micrô|máy ảnh|cho phép|bỏ qua|trang chủ|dữ liệu|trợ lý|chăm sóc|cài đặt|bắt đầu|dừng|ví dụ|tạm dừng|nói a trong 5 giây|nhìn vào giữa|xong|thử lại|đã lưu|chưa có phép đo|tải xuống|đang chuẩn bị|gửi|tin nhắn|không khả dụng|Phép đo, không phải chẩn đoán.|Dữ liệu khách chỉ ở trong phiên này.|Minh họa cuộc gọi. Không gọi thật.|nghe cuộc gọi|bệnh viện gần đây|Giọng Kokoro: chỉ tiếng Anh.|riêng tư|điều khoản|hủy|đăng xuất"),
        ("th", "ไทย", "ภาษา|ดำเนินการต่อ|ผู้เยี่ยมชม|สร้างบัญชี|เข้าสู่ระบบ|อีเมล|รหัสผ่าน|ชื่อ|ฉันยอมรับข้อกำหนดและนโยบายความเป็นส่วนตัว|ยืนยันอีเมล|รหัส|สิทธิ์|ไมโครโฟน|กล้อง|อนุญาต|ข้าม|หน้าหลัก|ข้อมูล|ผู้ช่วย|การดูแล|การตั้งค่า|เริ่ม|หยุด|ตัวอย่าง|พัก|พูดอาเป็นเวลา 5 วินาที|มองตรงกลาง|เสร็จแล้ว|ลองอีกครั้ง|บันทึกแล้ว|ยังไม่มีการวัด|ดาวน์โหลด|กำลังเตรียม|ส่ง|ข้อความ|ไม่พร้อมใช้งาน|เป็นการวัด ไม่ใช่การวินิจฉัย|ข้อมูลผู้เยี่ยมชมอยู่ในเซสชันนี้เท่านั้น|สาธิตการโทร ไม่มีการโทรจริง|ฟังการโทร|โรงพยาบาลใกล้เคียง|เสียง Kokoro: ภาษาอังกฤษเท่านั้น|ความเป็นส่วนตัว|ข้อกำหนด|ยกเลิก|ออกจากระบบ"),
        ("id", "Bahasa Indonesia", "bahasa|lanjut|tamu|buat akun|masuk|email|kata sandi|nama|Saya menyetujui ketentuan dan kebijakan privasi|verifikasi email|kode|izin|mikrofon|kamera|izinkan|lewati|beranda|data|asisten|perawatan|pengaturan|mulai|berhenti|contoh|jeda|ucapkan ah selama 5 detik|lihat ke tengah|selesai|coba lagi|tersimpan|belum ada pengukuran|unduh|menyiapkan|kirim|pesan|tidak tersedia|Pengukuran, bukan diagnosis.|Data tamu hanya ada di sesi ini.|Demo panggilan. Tidak ada panggilan nyata.|dengarkan panggilan|rumah sakit terdekat|Suara Kokoro: hanya bahasa Inggris.|privasi|ketentuan|batal|keluar"),
        ("pl", "Polski", "język|kontynuuj|gość|utwórz konto|zaloguj się|e-mail|hasło|imię|Akceptuję warunki i politykę prywatności|potwierdź e-mail|kod|uprawnienia|mikrofon|aparat|zezwól|pomiń|główna|dane|asystent|opieka|ustawienia|rozpocznij|zatrzymaj|przykład|pauza|mów a przez 5 sekund|patrz na środek|gotowe|spróbuj ponownie|zapisano|brak pomiarów|pobierz|przygotowanie|wyślij|wiadomość|niedostępne|Pomiary, nie diagnoza.|Dane gościa pozostają w tej sesji.|Demonstracja. Połączenie nie jest wykonywane.|odtwórz rozmowę|pobliskie szpitale|Głos Kokoro: tylko angielski.|prywatność|warunki|anuluj|wyloguj się"),
        ("nl", "Nederlands", "taal|doorgaan|gast|account maken|inloggen|e-mail|wachtwoord|naam|Ik ga akkoord met de voorwaarden en het privacybeleid|e-mail bevestigen|code|toestemmingen|microfoon|camera|toestaan|overslaan|start|gegevens|assistent|zorg|instellingen|starten|stoppen|voorbeeld|pauze|zeg 5 seconden ah|kijk naar het midden|klaar|opnieuw proberen|opgeslagen|nog geen metingen|downloaden|voorbereiden|versturen|bericht|niet beschikbaar|Metingen, geen diagnose.|Gastgegevens blijven in deze sessie.|Demonstratie. Er wordt niet gebeld.|gesprek afspelen|ziekenhuizen dichtbij|Kokoro-stem: alleen Engels.|privacy|voorwaarden|annuleren|uitloggen")
    ]
}

@MainActor @Observable final class VentureLocale {
    var language: VentureLanguage {
        didSet { UserDefaults.standard.set(language.id, forKey: "venture.language") }
    }
    init() {
        let saved = UserDefaults.standard.string(forKey: "venture.language")
        language = VentureLanguage.all.first { $0.id == saved } ?? VentureLanguage.all[0]
    }
    func t(_ key: VentureCopy) -> String { language.text(key) }
    func support(_ key: VentureSupportCopy) -> String {
        VentureSupportCopy.text(key, language: language.id)
    }

    var hasTranslatedSupport: Bool { ["en", "hi", "es"].contains(language.id) }
}

// New voice and care guidance is authored offline in these three languages.
// Other languages retain the existing translated controls and show an explicit
// English-guidance notice; we never imply that these paragraphs were translated.
enum VentureSupportCopy: Int, CaseIterable, Hashable {
    case voiceCheck, results, getHelp, voiceTip, openSpeech, speechPrompt, speechNote
    case recordingCaptured, retryQuality, quality, pitch, voicedTime, pitchVariation, loudnessVariation, words
    case measured, resultIntro, modelTitle, modelNote, nextTitle, nextNote, careIntro
    case clinic, clinicNote, telehealth, telehealthNote, voiceCare, voiceCareNote, memoryCare, memoryCareNote
    case visitPlan, visitPlanNote, source, share, directions, noNearby, analyzing, progress, englishNotice, variationNote
    case researchTitle, researchSimilarity, researchNote

    static func text(_ key: Self, language: String) -> String {
        let words = translations[language] ?? translations["en"]!
        return words[key.rawValue]
    }

    private static let translations: [String: [String]] = [
        "en": [
            "voice check", "your voice results", "get help", "sit somewhere quiet. hold your phone a hand's length away and use your comfortable voice.",
            "tell us about your day", "describe something you did today for 20 seconds, in your own words.", "optional · speech recognition runs on this device when available for your language.",
            "recording captured", "repeat in a quieter place", "recording quality", "voice pitch", "voiced time", "pitch variation", "loudness variation", "words captured",
            "measured signals", "a starting point for care", "disease screening unavailable", "these voice features cannot identify or rule out alzheimer's, parkinson's, or a type of dementia. a clinician can help understand changes you notice.",
            "one small next step", "if your voice, memory, or movement has changed, write down when it started and arrange a primary care visit. your concerns matter even if a recording looks clear.",
            "support, wherever you live. choose a step that works for you; these options support wellbeing and access to care.",
            "find a clinic", "look for a local clinic or community health worker. ask about fees, transport, interpreters, and a phone appointment before travelling.",
            "talk from home", "ask your clinic if a phone or video appointment is possible. write down your questions and gather your medication list. a phone visit may suit a slow connection.",
            "care for your voice", "drink water and give a tired voice breaks. avoid smoke, shouting, and whispering. ongoing hoarseness or effort to speak is a reason to talk with a clinician.",
            "make daily life easier", "use notes and a simple routine. keep everyday items in one place and stay connected with people you trust. noticeable memory changes or trouble with daily tasks deserve a medical review.",
            "prepare for a visit", "note the changes you noticed, when they began, and how they affect your day. bring your medicines and, if you want, someone you trust. ask whether speech therapy or a specialist review would help.",
            "read the guidance", "share voice summary", "open in maps", "no nearby clinic found. try maps or a local health service; location access is optional.", "reviewing your recording", "voice samples", "new voice and support guidance is shown in english.", "variation is the spread of pitch or loudness divided by its average. recording quality and variation describe this recording, not your health; noise, effort, and the microphone can affect them.",
            "research model comparison", "source study similarity", "comparison with a small spanish research dataset. this cannot tell whether you have parkinson's, another condition, or any form of dementia. this number is not your chance of having a disease."
        ],
        "hi": [
            "आवाज़ की जाँच", "आपकी आवाज़ के परिणाम", "मदद लें", "शांत जगह बैठें। फ़ोन को एक हाथ की दूरी पर रखें और अपनी सहज आवाज़ में बोलें।",
            "अपने दिन के बारे में बताएँ", "आज आपने जो किया, उसे अपने शब्दों में 20 सेकंड तक बताएँ।", "वैकल्पिक · आपकी भाषा के लिए उपलब्ध होने पर आवाज़ की पहचान इसी डिवाइस पर होती है।",
            "रिकॉर्डिंग मिली", "शांत जगह फिर कोशिश करें", "रिकॉर्डिंग की गुणवत्ता", "आवाज़ की पिच", "आवाज़ की अवधि", "पिच में बदलाव", "आवाज़ की तीव्रता में बदलाव", "पहचाने गए शब्द",
            "मापे गए संकेत", "देखभाल की ओर पहला कदम", "बीमारी की जाँच उपलब्ध नहीं", "आवाज़ के ये संकेत अल्ज़ाइमर, पार्किंसन या किसी प्रकार के डिमेंशिया की पहचान या उसे खारिज नहीं कर सकते। डॉक्टर आपके अनुभव किए बदलाव समझने में मदद कर सकते हैं।",
            "एक छोटा अगला कदम", "आवाज़, याददाश्त या चलने-फिरने में बदलाव हो तो लिखें कि वह कब शुरू हुआ और प्राथमिक स्वास्थ्य सेवा से संपर्क करें। स्पष्ट रिकॉर्डिंग के बाद भी आपकी चिंता महत्वपूर्ण है।",
            "आप जहाँ भी रहें, मदद मिल सकती है। अपनी स्थिति के अनुसार कदम चुनें; ये विकल्प स्वास्थ्य और देखभाल तक पहुँच में मदद करते हैं।",
            "क्लिनिक खोजें", "स्थानीय क्लिनिक या सामुदायिक स्वास्थ्य कर्मी से संपर्क करें। जाने से पहले शुल्क, परिवहन, दुभाषिए और फ़ोन पर परामर्श के बारे में पूछें।",
            "घर से परामर्श लें", "क्लिनिक से पूछें कि फ़ोन या वीडियो पर परामर्श हो सकता है या नहीं। अपने सवाल और दवाओं की सूची तैयार रखें। धीमे इंटरनेट पर फ़ोन से बात करना आसान हो सकता है।",
            "अपनी आवाज़ की देखभाल करें", "पानी पिएँ और थकी आवाज़ को आराम दें। धुएँ, चिल्लाने और फुसफुसाने से बचें। लगातार आवाज़ बैठना या बोलने में मेहनत लगना डॉक्टर से बात करने का कारण है।",
            "रोज़मर्रा की ज़िंदगी आसान बनाएँ", "नोट्स और सरल दिनचर्या अपनाएँ। रोज़ की चीज़ें एक जगह रखें और भरोसेमंद लोगों के संपर्क में रहें। याददाश्त में स्पष्ट बदलाव या रोज़ के काम में कठिनाई हो तो डॉक्टर से सलाह लें।",
            "मुलाक़ात की तैयारी करें", "बदलाव कब शुरू हुए और दिन पर उनका क्या असर है, यह लिखें। दवाएँ और चाहें तो किसी भरोसेमंद व्यक्ति को साथ लें। पूछें कि स्पीच थेरेपी या विशेषज्ञ से सलाह उपयोगी होगी या नहीं।",
            "मार्गदर्शन पढ़ें", "आवाज़ का सार साझा करें", "मैप में खोलें", "पास में क्लिनिक नहीं मिला। मैप या स्थानीय स्वास्थ्य सेवा से मदद लें; लोकेशन देना वैकल्पिक है।", "रिकॉर्डिंग की समीक्षा हो रही है", "आवाज़ के नमूने", "नई आवाज़ और सहायता की जानकारी अंग्रेज़ी में दिखाई गई है।", "बदलाव का मान पिच या आवाज़ की तीव्रता के फैलाव को उसके औसत से भाग देकर मिलता है। गुणवत्ता और बदलाव इस रिकॉर्डिंग का वर्णन करते हैं, आपकी सेहत का नहीं। शोर, बोलने के प्रयास और माइक्रोफ़ोन का इन पर असर हो सकता है।",
            "शोध मॉडल से तुलना", "मूल अध्ययन से समानता", "यह स्पैनिश भाषा के एक छोटे शोध डेटा से तुलना है। इससे पार्किंसन, किसी अन्य बीमारी या किसी प्रकार के डिमेंशिया का पता नहीं चल सकता। यह संख्या आपको बीमारी होने की संभावना नहीं है।"
        ],
        "es": [
            "revisión de voz", "tus resultados de voz", "obtener ayuda", "siéntate en un lugar tranquilo. mantén el teléfono a un palmo de distancia y usa tu voz habitual.",
            "cuéntanos sobre tu día", "describe algo que hiciste hoy durante 20 segundos, con tus propias palabras.", "opcional · el reconocimiento de voz funciona en este dispositivo cuando está disponible para tu idioma.",
            "grabación capturada", "repite en un lugar más tranquilo", "calidad de grabación", "tono de voz", "tiempo de voz", "variación del tono", "variación del volumen", "palabras capturadas",
            "señales medidas", "un primer paso hacia el cuidado", "evaluación de enfermedades no disponible", "estas características de la voz no pueden identificar ni descartar alzhéimer, párkinson ni un tipo de demencia. un profesional puede ayudarte a entender los cambios que notas.",
            "un pequeño paso siguiente", "si tu voz, memoria o movimiento ha cambiado, anota cuándo empezó y pide una consulta de atención primaria. tus inquietudes importan aunque la grabación sea clara.",
            "apoyo dondequiera que vivas. elige un paso que te sirva; estas opciones apoyan el bienestar y el acceso a atención.",
            "encontrar una clínica", "busca una clínica local o un agente comunitario de salud. pregunta por tarifas, transporte, intérpretes y citas por teléfono antes de viajar.",
            "consultar desde casa", "pregunta si tu clínica ofrece citas por teléfono o video. prepara tus preguntas y una lista de medicamentos. una llamada puede servir si la conexión es lenta.",
            "cuidar tu voz", "bebe agua y descansa la voz cuando esté cansada. evita el humo, gritar y susurrar. la ronquera persistente o el esfuerzo al hablar merece una consulta.",
            "facilitar la vida diaria", "usa notas y una rutina sencilla. guarda tus objetos cotidianos en un mismo lugar y mantén contacto con personas de confianza. los cambios claros de memoria o la dificultad con tareas diarias merecen una revisión médica.",
            "preparar una consulta", "anota qué cambió, cuándo comenzó y cómo afecta a tu día. lleva tus medicamentos y, si quieres, alguien de confianza. pregunta si la terapia del habla o una revisión especializada podría ayudar.",
            "leer la guía", "compartir resumen de voz", "abrir en mapas", "no se encontró una clínica cercana. prueba mapas o un servicio local; compartir ubicación es opcional.", "revisando tu grabación", "muestras de voz", "la nueva guía de voz y apoyo se muestra en inglés.", "la variación es la dispersión del tono o volumen dividida por su promedio. la calidad y la variación describen esta grabación, no tu salud; el ruido, el esfuerzo y el micrófono pueden influir.",
            "comparación con un modelo de investigación", "similitud con el estudio original", "comparación con un pequeño conjunto de datos de investigación en español. no puede determinar si tienes párkinson, otra enfermedad o algún tipo de demencia. este número no es tu probabilidad de tener una enfermedad."
        ]
    ]
}
